// @ts-check
/** @type{import('../../../src/assets/data/interfaces').TranslationDict} */
export default {
  RARITY_NORMAL: 'ノーマル',
  RARITY_MAGIC: 'マジック',
  RARITY_RARE: 'レア',
  RARITY_UNIQUE: 'ユニーク',
  RARITY_GEM: 'ジェム',
  RARITY_CURRENCY: 'カレンシー',
  RARITY_DIVCARD: '卜占カード',
  RARITY_QUEST: 'クエスト',
  MAP_TIER: / \(ティア (\d+)\)$/,
  MAP_ITEM_QUANTITY: 'アイテム数量: ',
  MAP_ITEM_RARITY: 'アイテムレアリティ: ',
  MAP_MONSTER_PACK_SIZE: 'モンスターパックサイズ: ',
  MAP_MORE_MAPS: 'より多くのマップ: ',
  MAP_MORE_SCARABS: 'より多くのスカラベ: ',
  MAP_MORE_CURRENCY: 'より多くのカレンシー: ',
  MAP_MORE_DIVINATION_CARDS: 'より多くの卜占カード: ',
  MAP_COMPLETION_REWARD: /^報酬: フォイル (.*)$/,
  RARITY: 'レアリティ: ',
  ITEM_CLASS: 'アイテムクラス: ',
  ITEM_LEVEL: 'アイテムレベル: ',
  CORPSE_LEVEL: '死体レベル: ',
  TALISMAN_TIER: 'タリスマンティア: ',
  GEM_LEVEL: 'レベル: ',
  STACK_SIZE: 'スタックサイズ: ',
  SOCKETS: 'ソケット: ',
  QUALITY: '品質: ',
  MEMORY_STRANDS: 'メモリストランド: ',
  PHYSICAL_DAMAGE: '物理ダメージ: ',
  ELEMENTAL_DAMAGE: '元素ダメージ: ',
  CRIT_CHANCE: 'クリティカル率: ',
  ATTACK_SPEED: '秒間アタック回数: ',
  ARMOUR: 'アーマー: ',
  EVASION: '回避値: ',
  ENERGY_SHIELD: 'エナジーシールド: ',
  TAG_WARD: 'ウォード: ',
  BLOCK_CHANCE: 'ブロック率: ',
  CORRUPTED: 'コラプト',
  UNIDENTIFIED: '未鑑定',
  ITEM_SUPERIOR: /^上位 (.*)$/,
  MAP_BLIGHTED: /^ブライト (.*)$/,
  MAP_BLIGHT_RAVAGED: /^ブライト壊滅 (.*)$/,
  INFLUENCE_SHAPER: 'シェイパーのアイテム',
  INFLUENCE_ELDER: 'エルダーのアイテム',
  INFLUENCE_CRUSADER: 'クルセイダーのアイテム',
  INFLUENCE_HUNTER: 'ハンターのアイテム',
  INFLUENCE_REDEEMER: 'リディーマーのアイテム',
  INFLUENCE_WARLORD: 'ウォーロードのアイテム',
  SECTION_SYNTHESISED: 'シンセサイズアイテム',
  ITEM_SYNTHESISED: /^シンセサイズ (.*)$/,
  VEILED_PREFIX: 'ヴェールプレフィックスモッド',
  VEILED_SUFFIX: 'ヴェールサフィックスモッド',
  FLASK_CHARGES: /^現在 \d+ チャージを持っている$/,
  METAMORPH_HELP: 'テインの研究室で他の4つの異なるサンプルと組み合わせてください。',
  BEAST_HELP: '右クリックしてビースタリーに追加します。',
  VOIDSTONE_HELP: 'アトラスにはめ込んでマップを強化します。',
  METAMORPH_BRAIN: /^.* 脳$/,
  METAMORPH_EYE: /^.* 眼$/,
  METAMORPH_LUNG: /^.* 肺$/,
  METAMORPH_HEART: /^.* 心臓$/,
  METAMORPH_LIVER: /^.* 肝臓$/,
  CANNOT_USE_ITEM: 'このアイテムは使用できません。ステータスは無視されます',
  QUALITY_ANOMALOUS: /^アノーマラス (.*)$/,
  QUALITY_DIVERGENT: /^ダイバージェント (.*)$/,
  QUALITY_PHANTASMAL: /^ファンタズマル (.*)$/,
  AREA_LEVEL: 'エリアレベル: ',
  HEIST_WINGS_REVEALED: 'ウィング解放数: ',
  HEIST_BLUEPRINT_TARGET: 'ハイストターゲット: ',
  HEIST_BLUEPRINT_ENCHANTS: 'エンチャントされた武具',
  HEIST_BLUEPRINT_TRINKETS: '盗賊のトリンケットまたはカレンシー',
  HEIST_BLUEPRINT_GEMS: '珍しいジェム',
  HEIST_BLUEPRINT_REPLICAS: 'レプリカまたは実験的アイテム',
  HEIST_CONTRACT_JOB: /^(?<job>.+) が必要です \(レベル (?<level>\d+)(?:\s*\(未達\))?\)$/,
  HEIST_JOB_LOCKPICKING: '鍵開け',
  HEIST_JOB_BRUTEFORCE: '力技',
  HEIST_JOB_PERCEPTION: '知覚',
  HEIST_JOB_DEMOLITION: '解体',
  HEIST_JOB_COUNTERTHAUMATURGY: '対魔術',
  HEIST_JOB_TRAPDISARMAMENT: '罠解除',
  HEIST_JOB_AGILITY: '敏捷性',
  HEIST_JOB_DECEPTION: '欺瞞',
  HEIST_JOB_ENGINEERING: '工学',
  HEIST_CONTRACT_TARGET: /^ハイストターゲット: .+ \((.+)\)$/,
  HEIST_TARGET_PRICELESS: 'プライスレス',
  MIRRORED: 'ミラー',
  SPLIT: 'スプリット',
  MODIFIER_LINE: /^(?<type>[^「」]+?)\s*(?:「(?<name>[^「」]*)」)?\s*(?:\(ティア: (?<tier>\d+)\))?\s*(?:\(ランク: (?<rank>\d+)\))?$/,
  PREFIX_MODIFIER: 'プレフィックスモッド',
  SUFFIX_MODIFIER: 'サフィックスモッド',
  CRAFTED_PREFIX: 'マスタークラフトプレフィックスモッド',
  CRAFTED_SUFFIX: 'マスタークラフトサフィックスモッド',
  IMPLICIT_MODIFIER: '暗黙モッド',
  FRACTURED_PREFIX: 'フラクチャードプレフィックスモッド',
  FRACTURED_SUFFIX: 'フラクチャードサフィックスモッド',
  UNSCALABLE_VALUE: ' — スケールできない値',
  CORRUPTED_IMPLICIT: '腐敗暗黙モッド',
  MODIFIER_INCREASED: /^(.+?)%増加$/,
  INCURSION_OPEN: 'Open Rooms:',
  INCURSION_OBSTRUCTED: 'Obstructed Rooms:',
  EATER_IMPLICIT: /^世界を喰らうもの 暗黙モッド 「(?<rank>.+)」$/,
  EXARCH_IMPLICIT: /^灼熱の代行者 暗黙モッド 「(?<rank>.+)」$/,
  ELDRITCH_MOD_R1: '小',
  ELDRITCH_MOD_R2: '小中',
  ELDRITCH_MOD_R3: '中',
  ELDRITCH_MOD_R4: '大中',
  ELDRITCH_MOD_R5: '大',
  ELDRITCH_MOD_R6: '完全',
  SENTINEL_CHARGE: 'チャージ: ',
  SHAPER_MODS: ['of Shaping', "The Shaper's"],
  ELDER_MODS: ['of the Elder', "The Elder's"],
  CRUSADER_MODS: ["Crusader's", 'of the Crusade'],
  HUNTER_MODS: ["Hunter's", 'of the Hunt'],
  REDEEMER_MODS: ['of Redemption', "Redeemer's"],
  WARLORD_MODS: ["Warlord's", 'of the Conquest'],
  DELVE_MODS: ['Subterranean', 'of the Underground'],
  VEILED_MODS: ['Chosen', 'of the Order'],
  INCURSION_MODS: ["Guatelitzi's", "Xopec's", "Topotante's", "Tacati's", "Matatl's", 'of Matatl', "Citaqualotl's", 'of Citaqualotl', 'of Tacati', 'of Guatelitzi', 'of Puhuarte'],
  FOIL_UNIQUE: 'フォイルユニーク',
  UNMODIFIABLE: '変更不可',
  FOULBORN_NAME: /^フォウルボーン (.*)$/,
  FOULBORN_MODIFIER: 'フォウルボーンユニークモッド',
  // ---
  CHAT_SYSTEM: /^: (?<body>.+)$/,
  CHAT_TRADE: /^\$(?:<(?<guild_tag>.+?)> )?(?<char_name>.+?): (?<body>.+)$/,
  CHAT_GLOBAL: /^#(?:<(?<guild_tag>.+?)> )?(?<char_name>.+?): (?<body>.+)$/,
  CHAT_PARTY: /^%(?:<(?<guild_tag>.+?)> )?(?<char_name>.+?): (?<body>.+)$/,
  CHAT_GUILD: /^&(?:<(?<guild_tag>.+?)> )?(?<char_name>.+?): (?<body>.+)$/,
  CHAT_WHISPER_TO: /^@To (?<char_name>.+?): (?<body>.+)$/,
  CHAT_WHISPER_FROM: /^@From (?:<(?<guild_tag>.+?)> )?(?<char_name>.+?): (?<body>.+)$/,
  CHAT_WEBTRADE_GEM: /^level (?<gem_lvl>\d+) (?<gem_qual>\d+)% (?<gem_name>.+)$/
}
